regionalDR:
  - name: resilient # Matches with ClusterSet
    globalnetEnabled: false # Support for overlapping CIDR
    clusters: # Pair of clusters, make sure to create each in a different region
      primary:
        name: ocp-primary
        version: 4.14.12
        # See OpenShift documentation for install config spec
        # https://docs.openshift.com/container-platform/4.14/installing/installing_aws/installing-aws-customizations.html
        install_config:
          apiVersion: v1
          metadata:
            name: ocp-primary
          baseDomain: example-domain.com
          controlPlane:
            name: master
            replicas: 3
            platform:
              aws:
                type: m5.2xlarge
                zones:
                  - ca-central-1a
          compute:
            - name: worker
              replicas: 5
              platform:
                aws:
                  type: m5.2xlarge
                  zones:
                    - ca-central-1a
          networking:
            clusterNetwork:
              - cidr: 10.128.0.0/14
                hostPrefix: 23
            machineNetwork:
              - cidr: 10.0.0.0/16
            networkType: OpenShiftSDN
            serviceNetwork:
              - 172.30.0.0/16
          platform:
            aws:
              region: ca-central-1
              userTags:
                project: ValidatedPatterns

          publish: External
          sshKey: ""
          pullSecret: ""
      secondary:
        name: ocp-secondary
        version: 4.14.12
        install_config:
          apiVersion: v1
          metadata:
            name: ocp-secondary
          baseDomain: example-domain.com
          controlPlane:
            name: master
            replicas: 3
            platform:
              aws:
                type: m5.2xlarge
                zones:
                  - eu-central-1a
          compute:
            - name: worker
              replicas: 5
              platform:
                aws:
                  type: m5.2xlarge
                  zones:
                    - eu-central-1a
          networking:
            clusterNetwork:
              - cidr: 10.132.0.0/14
                hostPrefix: 23
            machineNetwork:
              - cidr: 10.1.0.0/16
            networkType: OpenShiftSDN
            serviceNetwork:
              - 172.31.0.0/16
          platform:
            aws:
              region: eu-central-1
              userTags:
                project: ValidatedPatterns

          publish: External
          sshKey: ""
          pullSecret: ""
    # List of sync policy intervals: RPO should be larger than the sync time.
    # If your sync process takes 3 mins, the interval should be at least 4-5 mins.
    intervals:
      - 1m
      - 2m
